# Generated by Django 2.2.5 on 2019-11-25 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='tax_number',
            field=models.IntegerField(default=9, unique=True, verbose_name='Tax number'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='beer',
            name='color',
            field=models.PositiveSmallIntegerField(choices=[(4, 'brown'), (3, 'amber'), (2, 'black'), (1, 'yellow')], default=1, verbose_name='Color'),
        ),
    ]
